### PR TITLE
RemoveAll was clearing the wrong array if removeOneTimeListeners was set to true

### PR DESCRIPTION
**Pull request by prodigga**
Just a small issue I noticed.

I was not sure how to update the tests to catch this issue, I have not worked with testing libraries before to be honest so I am not sure what the correct workflow is.

### CODE REVIEW

**Review by SixWays — CHANGES_REQUESTED** [review]
In general, I like the idea. A few small things first though - firstly, could you run the profiler tests on your version vs head and see if there are any performance differences? I doubt there'll be anything significant, but I've been careful to push performance as hard as possible, hence using arrays instead of lists etc. Secondly,  IterateAndInvoke hard-codes onceListeners for removal. Thirdly and least importantly, not sure if it's github but whitespace seems a bit all over the place - I'll likely do some cleanup and conform it to the existing style anyway but anything you can do on that front would help.

**Comment by prodigga** [comment]
HI there

Wow, ok, so I never intended to push anything more than the first commit that is listed here (https://github.com/SixWays/Relay/pull/2/commits/b3da0330bd93510dfe32b29cbd5b90feecf7e540).

I am a GitHub noob, I didn't realise that it would append any other changes I push to the branch to my PR...!

Well..now that we are here...

1) So, this isn't actually the most up-to-date version of the stuff I was working on. I am pushing the rest of my changes now (They are changes I made yesterday, and so do not contain any whitespace fixes/etc). Again, I didn't realise this was going up on the PR, so I pushed the first part, and only committed the other parts of my work.

2) The white spaces - I have no idea why it looks like that. It looks nothing like that on my end. 👎 I tried my best to confirm to the style of the repo ( '{'s on the same line as method decorations, inlining things that you had inlined too (ie: ` if (wasAdded) _RelayDebugger.DebugAddListener(this, listener);`. My RelayDelegateCollection class does not reflect these conventions yet but, again, it was WIP and you weren't supposed to see 😅

3) I have been benchmarking the changes I try out as I go on. I have been maintaining a spreadsheet. [You can view it here.](https://docs.google.com/spreadsheets/d/13C7Lv7owXwbK4-v2Rl2xzy88TgK8wOm1urJhZ4m0Tc4/edit?usp=sharing). _Before_ is the repo as is without any of my changes. _Change6_ is where I currently am. (https://github.com/SixWays/Relay/pull/2/commits/04180c7674e630187abf26ad2fa15d33c2634359) (_Change7_ was reverted).

Each Change has a comment associated with it to let you know what was changed/attempted to improve performance.

It is still not as good as what you had for _Populate (Allow Duplicates)_. 2x as slow as your version. Though _Populate (No Duplicates)_ is 50% faster than your version. 🤔

I was trying to get much closer to the speeds you were getting for _Populate (Allow Duplicates)_ before I was going to suggest any of these changes.

**Comment by SixWays** [comment]
Just fixed the unit tests and also added a "Run All" profile option. This also outputs a CSV string of all the results so you can easily update your spreadsheet without manually entering values each time. In case you're not aware, you'll have to get google sheets to paste as columns as shown.
2018-05-27 11_01_37-window

**Comment by prodigga** [comment]
This is cool! No, I don't have results for other profiles, I should've been keeping track of em as I went along but I got kind of fixated on trying to get Populate (Allow Duplicates) working faster, hah.

I'm not sure if I will put any more work into it. I was inspired to do this after noticing the RemoveAll error. Less repetition would mean less errors like this at this cost of performance. But... Thinking about it further... we could have both performance and stability with broader test coverage. Maybe that's what should be focused on? Ensuring the tests dont miss things like the RemoveAll/onceListener bug in the future. There isn't that much code to maintain anyway, so maybe the repetition isn't a _huge_ deal when combined with thorough unit tests.

**Comment by SixWays** [comment]
Fair enough. I'm still intrigued by the improvement to non-dupe population though - any thoughts why that's the case? Wondering if there's something we could do to improve that without altering how regular population works. But as you say - with unit test coverage, things are working well as is.

**Comment by SixWays** [comment]
Since it's been a while, I'm going to close this if there are no objections?

**Comment by prodigga** [comment]
Yeah, thats cool. Sorry I didn't get around to replying, I got caught up in my work!

To answer your question, I have no idea why that's the case. :)

Go ahead and close! 👍

**Pull request closed without merging**
